### ISSUE TITLE
nan loss

### ISSUE THREAD

**Issue by jimmy-dq** [junchen14/LoMaR#2]
Hi junchen,
Thanks for your great work. Recently when I try your local reconstruction training, I found the NaN loss is easily occurred during the training. Any suggestions for this? Thanks.

**Comment by junchen14** [comment]
Hi can you share more about your training details so I can better understand the problem. Actually I seldom face nan problem in my experiments.

**Comment by jimmy-dq** [comment]
> Hi can you share more about your training details so I can better understand the problem. Actually I seldom face nan problem in my experiments.

Thanks for your reply. I disable the iRPE and use my own dataset for training. The nan loss occurs at the beginning (i.e., epoch-8). This problem is solved when I disable the AMP training, i.e. amp.autocast(enabled=False).
